### ISSUE TITLE
sodium_init() isn't itself thread safe

### ISSUE THREAD

**Issue by stouset** [dnaq/sodiumoxide#107]
[The implementation](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/core.c#L26) isn't thread-safe, so care needs to be taken not to call this from threads. One approach is to use [`std::sync::Once`](https://github.com/stouset/secrets/blob/master/src/sodium.rs#L29).

**Comment by dnaq** [comment]
See #95
