### ISSUE TITLE
Incrementing nonce fails

### ISSUE THREAD

**Issue by zetok** [dnaq/sodiumoxide#111]
on 7cd94ccd48a9b0cc07fc7a52a08a3e3de9efebcb

Reproducible: Always

Steps to reproduce:
1. try to increment `Nonce` with `increment_le()`
2. fails

**Comment by zetok** [comment]
https://github.com/zetok/tox ← tests for incrementing nonce fail

**Comment by dnaq** [comment]
Your code is incorrect. There are two methods for incrementing nonces. increment_le which returns a new nonce and increment_le_inplace which increments the old one in place. You are calling increment_le and throwing away the return value.

**Comment by zetok** [comment]
Right, thanks. Sorry for the issue - I thought that Rust would have warned me about unused return value :/

**Comment by dnaq** [comment]
Only types that have the #[must_use] attribute. I might add it to all types in sodiumoxide though since it will help out with issues like yours.
