### ISSUE TITLE
Expose sealed box functions

### ISSUE THREAD

**Issue by Fraser999** [dnaq/sodiumoxide#113]
We have a need for the anonymous public-key functions described at https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html

I'd be happy to start work on a pull request for this, but I'm unsure about how you would want the functions and new module named, given that e.g. `crypto::box_::*` already exists as an alias for the authenticated public-key functions in `curve25519xsalsa20poly1305`.

**Comment by dirvine** [comment]
+1 Excellent. This will be very handy indeed.

**Comment by dnaq** [comment]
Also see #100

**Comment by Fraser999** [comment]
OK - we can use the suggested workaround from the other issue.  Thanks for the quick response.
