### ISSUE TITLE
Ability to statically link against libsodium

### ISSUE THREAD

**Issue by untitaker** [dnaq/sodiumoxide#116]
I want to deploy my application binary on Linux distributions that don't have a reasonably up-to-date libsodium in their package repositories. That would mean I'd have to manually compile libsodium there, and keep it up-to-date. I wish that sodiumoxide were able to statically link libsodium so that I'd only have to worry about updating it on the build machine.

**Comment by dirvine** [comment]
I do not think you are prevented from that. It may not be obvious, but link only the .a files and you are good. If building your own then pass `--disable-shared` or similar in the configure step. ./configure --help will show you. Then you will be statically linked.  Note in linux etc. if there is also a shared lib the linker will prefer it in many cases.

**Comment by untitaker** [comment]
Oh wow thanks, that actually worked: https://github.com/untitaker/mysteryshack/pull/41

**Comment by ruuda** [comment]
Is there anything I need to do to get this to work besides setting the `SODIUM_STATIC` environment variable during `cargo build`? With version 0.0.16, when I set `SODIUM_STATIC` I still get a dependency on `libsodium.so`.
