### ISSUE TITLE
Stream hasher 

### ISSUE THREAD

**Issue by Phaiax** [dnaq/sodiumoxide#119]
Does sodium have a stream hasher for sodiumoxide::crypto::hash / sha256?
If it does, I would like to request bindings.

**Comment by jedisct1** [comment]
It does.

**Comment by dnaq** [comment]
I'm a bit behind on new releases at the moment, but I'll look into your issue when I've got a little more time.

**Comment by Phaiax** [comment]
thank you
      
      On 18.03.2016 06:57, dnaq wrote:
    
    
      I'm a bit behind on new releases at the moment, but I'll look
        into your issue when I've got a little more time.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub
