### ISSUE TITLE
SecretKey doesn't have impl AsRef<[u8]> but PublicKey does

### ISSUE THREAD

**Issue by danlarkin** [dnaq/sodiumoxide#120]
Firstly, why the discrepancy?

And secondly, how should one save the SecretKey generated from `gen_keypair` (if not by getting its bytes)?

**Comment by dnaq** [comment]
1. To reduce the risk of mishandling a secret key (e.g. sending the bytes
over the network without meaning to)
2. let SecretKey(ref skbytes) = sk;
