### ISSUE TITLE
when used as dependency, master fails to compile

### ISSUE THREAD

**Issue by zetok** [dnaq/sodiumoxide#123]
```
   Compiling sodiumoxide v0.0.9 (https://github.com/dnaq/sodiumoxide.git#a41a89ee)
 Documenting sodiumoxide v0.0.9 (https://github.com/dnaq/sodiumoxide.git#a41a89ee)
/home/zetok/.cargo/git/checkouts/sodiumoxide-b591577707ea1468/master/src/utils.rs:39:9: 39:30 error: unresolved name `ffi::sodium_increment` [E0425]
/home/zetok/.cargo/git/checkouts/sodiumoxide-b591577707ea1468/master/src/utils.rs:39         ffi::sodium_increment(x.as_mut_ptr(), x.len());
                                                                                             ^~~~~~~~~~~~~~~~~~~~~
/home/zetok/.cargo/git/checkouts/sodiumoxide-b591577707ea1468/master/src/utils.rs:39:9: 39:30 help: run `rustc --explain E0425` to see a detailed explanation
/home/zetok/.cargo/git/checkouts/sodiumoxide-b591577707ea1468/master/src/utils.rs:39:9: 39:30 error: unresolved name `ffi::sodium_increment` [E0425]
/home/zetok/.cargo/git/checkouts/sodiumoxide-b591577707ea1468/master/src/utils.rs:39         ffi::sodium_increment(x.as_mut_ptr(), x.len());
                                                                                             ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: aborting due to previous error
Could not compile `sodiumoxide`.
```
Newer master has even more errors.

`0.0.9` version on the other hand doesn't provide required features.

**Comment by dnaq** [comment]
Seems like you're building against an old version of libsodium, could you
try to update it?

**Comment by zetok** [comment]
Well, it tries to build against 0.0.9, as defined: https://github.com/dnaq/sodiumoxide/blob/27c731800501269e9191a3c9393a8e6fcb65c4ff/Cargo.toml#L14

**Comment by zetok** [comment]
>Seems like you're building against an old version of libsodium, could you try to update it?

And if the question was about the actual C lib, then no, I'm not building against an "old" version. I can make sodiumoxide compile, but the problem (i.e. default behaviour) where sodiumoxide simply fails to compile without taking additional steps remains.

**Comment by dnaq** [comment]
Which version of libsodium are you using?

**Comment by zetok** [comment]
1.0.8

**Comment by dnaq** [comment]
sodiumoxide master builds fine both for me and on travis, could you post a more extensive report?

**Comment by dnaq** [comment]
I just pushed 0.0.10 to crates.io, could you retry with that?

**Comment by zetok** [comment]
Thanks, that did it once I've updated deps to use 0.0.10 :)

The problem was compiling failure without those  steps: https://github.com/zetok/tox/tree/32b1b84b0987c300916cbb1ce7a5bbf81caa9b08#building
