### ISSUE TITLE
`GroupElement` is secret?

### ISSUE THREAD

**Issue by chzpa** [dnaq/sodiumoxide#126]
Why did you make [`crypto::scalarmult::curve25519::GroupElement`](https://github.com/dnaq/sodiumoxide/blob/9677d7edbcf359ed5ee84e7d819eea778f6760c6/src/crypto/scalarmult/curve25519.rs#L24) secret with commit f0852a8389e9e225873a5894587bbb88d7787f8f?

**Comment by dnaq** [comment]
The rationale for not having it secret was that it can represent a public value when using scalarmult for diffie-hellman. The rationale for making it secret is that it is also used to represent the shared secret when using it for diffie-hellman. Thus making it secret by default is the conservative choice (you can always access the underlying bytes if you need to copy the value to the network for example).
