### ISSUE TITLE
Resolve pitfalls for new users.

### ISSUE THREAD

**Issue by duesee** [dnaq/sodiumoxide#134]
I tried sodiumoxide today the first time. When working with the library I wanted to serialize some public and private keys to json so that I can reuse them later.

I used the version from crates.io (as I always do when working with Rust) and find that it is outdated. Some hours and a [SO question](https://stackoverflow.com/questions/38250632/serialize-sodiumoxides-publickey-into-json) later I was able to fix this using the GitHub version.

Is this library intended to be used over crates.io?

**Comment by dnaq** [comment]
I've been holding off on a new release pending more testing. That's why it
isn't on crates.io yet, but it will be soon.

**Comment by duesee** [comment]
Sounds good.

**Comment by dnaq** [comment]
6e9083472364dca172bbe0f950db97d269f18b3c closes the issue
