### ISSUE TITLE
Please add the missing ed25119->curve25519 conversion methods

### ISSUE THREAD

**Issue by cryptix** [dnaq/sodiumoxide#140]
I miss these two to port the [secret-handshake](https://github.com/auditdrivencrypto/secret-handshake) protocol to rust.

```
crypto_sign_ed25519_pk_to_curve25519
crypto_sign_ed25519_sk_to_curve25519
```

With a little guidance I could whip up a _leg work_-PR. I think the initial thing to do would be to add them to the underlying FFI crate, right?

**Comment by dnaq** [comment]
Please see #85 for precious discussions about this issue.
