### ISSUE TITLE
On Windows MSVC, libsodium binaries can't be found

### ISSUE THREAD

**Issue by LaylConway** [dnaq/sodiumoxide#142]
In the pre-compiled binaries for libsodium on Windows for the MSVC toolchain, the binaries are called "libsodium.lib". However, the line `println!("cargo:rustc-link-lib={0}=sodium", mode);` will only search for `sodium.lib`. On MSVC toolchain, lib should be prefixed. I don't know if the same problem occurs on the Windows GNU toolchain.

**Comment by dnaq** [comment]
I don't have access to MSVC, so it's hard for me to test your issue. I
would welcome a pull request that contains a windows build/testsuite using
appveyor though.
