### ISSUE TITLE
Add IETF versions of chacha20poly1305

### ISSUE THREAD

**Issue by nokaa** [dnaq/sodiumoxide#145]
Would you consider adding the IETF versions of chacha20poly1305? I believe that I've made the necessary additions, so I can submit a pull request.

**Comment by dnaq** [comment]
Hi. Yes, I would definitely consider it. There's a (closed) pull request with further discussion on the issue if you want to read more about previous discussions on the subject.

**Comment by dnaq** [comment]
Closed by 5d53fab116011dba7fd32eedf684b1e1106743d4
