### ISSUE TITLE
from_slice returns option. Why not result?

### ISSUE THREAD

**Issue by Deedasmi** [dnaq/sodiumoxide#148]
https://github.com/dnaq/sodiumoxide/blob/master/src/newtype_macros.rs#L16
 
Why does from_slice return an option rather than a result? Isn't a parsing error more like an error than a potential null?

**Comment by dnaq** [comment]
The reasoning was that

1. There's no meaningful error message (only one way it can go wrong)
2. There's no risk of an unused result leading to security issues

I'm not married to the idea though, but I don't know if the difference
between Option<T> and Result<(), T> is large enough to change it now.

**Comment by Deedasmi** [comment]
The biggest reason for me would be that it's inconsistent (aka unintuitive), and due to the way documentation is made it's undocumented. 

Additionally, if someone wanted to fork and add some more descriptive errors (decryption can fail in two ways, both that return `Err(())`) , the fork would require an API change. 

If nothing else, I think it should go into a todo list for a future api change, should one ever happen. I agree it's not a big enough issue to put out a breaking change just to fix it, but I would argue it should be fixed.
