### ISSUE TITLE
Can't serialize Key with rmp

### ISSUE THREAD

**Issue by kyrias** [dnaq/sodiumoxide#152]
I'm trying to serialize NaCl keys using the msgpack-rust library, but apparently it cannot deserialize them again because of the asymmetry in how the serialize and deserialize implementations for the Key struct. 3Hren/msgpack-rust#96

I'm a pretty beginner Rust programmer, so I don't fully understand how to do it myself, but would it be possible to have them implemented symmetrically, so that the msgpack-rust crate would be usable?

**Comment by dnaq** [comment]
I'll look into it as soon as msgpack-rust supports serde 0.9

**Comment by 3Hren** [comment]
It landed.

**Comment by kyrias** [comment]
Hm, I'm also getting `invalid type: byte array, expected $newtype` when trying to deserialize a `Nonce`, and happens with multiple serde using serializers.  Not quite sure what's going on.

**Comment by kyrias** [comment]
Gah, sorry, ignore this, was working in a checkout that didn't have the git version of sodiumoxide.

**Comment by dnaq** [comment]
Can you try the master branch of sodiumoxide and see if your issue has been
solved?

**Comment by kyrias** [comment]
Yeah, it works perfectly on master, thanks.
