### ISSUE TITLE
Explicit Clone impls for Copy types

### ISSUE THREAD

**Issue by kmcallister** [dnaq/sodiumoxide#164]
clippy gives a bunch of warnings of this form:

```
warning: you are implementing `Clone` explicitly on a `Copy` type
  --> src/newtype_macros.rs:2:9
   |
2  | /         impl Clone for $newtype {
3  | |             fn clone(&self) -> $newtype {
4  | |                 let &$newtype(v) = self;
5  | |                 $newtype(v)
6  | |             }
7  | |         }
   | |_________^
   | 
  ::: src/crypto/box_/curve25519xsalsa20poly1305.rs
```

Is there a good reason to `impl Clone` this way?

**Comment by dnaq** [comment]
The reason was that `#derive(Clone)` didn't work when the arrays are too large. This is a known limitation in rusts type-system.

So basically we're stuck between a rock and a hard place. Either the code doesn't compile, or we get clippy warnings, or we need to duplicate code.
