### ISSUE TITLE
Add Ed25519 to Curve25519 keys conversion

### ISSUE THREAD

**Issue by AljoschaMeyer** [dnaq/sodiumoxide#165]
[Ed25519 to Curve25519 key conversion](https://download.libsodium.org/libsodium/content/advanced/ed25519-curve25519.html) is not exposed in the rust api. I'm too new to crypto, C and Rust to feel comfortable writing a pull request for this without guidance though.

**Comment by dnaq** [comment]
Thanks for the offer. I've decided to not add support for those primitives
for now, please see #85 for earlier discussion on the issue.

**Comment by AljoschaMeyer** [comment]
Thank you for the quick reply. My use case is the same as the one use case that was provided in the issue you linked to: I want to implement [a protocol](https://github.com/auditdrivencrypto/secret-handshake) that uses the conversion with ephemeral keys. Incidentally the protocol was designed by @dominictarr who also chimed in the discussion in the issue.

So if this won't be added, could you point me to the right direction for what to do? Maintain a fork of the bindings? Create a different package for bindings to just these functions? Try to  translate [the implementation](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_sign/ed25519/ref10/keypair.c#L44) to rust?

**Comment by dnaq** [comment]
You don't need to fork, you just need to add bindings to the libsodium
functions that you need (in your own code).

I skimmed through the paper you linked, and I don't agree with a lot of the
contents in it. I don't have the time to give a detailed response, but are
you sure you need to use that protocol at all?

If you want to set up an authenticated key exchange I think you might be
better served by using a protocol designed for that purpose.

If you want to implement the protocol more as a learning experience, then
please for all means do so.

**Comment by AljoschaMeyer** [comment]
There's a [decentralized database/log](http://scuttlebot.io/) built on top of that protocol, and I'd like to write a client in rust. So if I want to talk to instances of the database, there's no way around using that protocol. If I had free choice of protocol to solve a specific usecase, I'd go with a more established protocol as well.
