### ISSUE TITLE
Please add support for multipart messages

### ISSUE THREAD

**Issue by Svedrin** [dnaq/sodiumoxide#166]
libsodium supports [multipart messages](https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html) through the `crypto_sign_init` / `crypto_sign_update` / `crypto_sign_final_{create,verify}` functions. Please add support for them to sodiumoxide. The underlying algorithm is subtly different, so I can't just easily use `crypto_sign` and get the same results.

Thanks :)

**Comment by dnaq** [comment]
Hashing the message with sha512 and signing the hash should give you the same results. Does that work for you?

**Comment by jedisct1** [comment]
Unfortunately not. Ed25519 requires a different context identifier.

**Comment by Svedrin** [comment]
Tried that. Unforatunately it doesn't work, because `crypto_sign_{init,update,final}` and `crypto_sign_detached` hash the messages differently :(

See [sign.c](https://github.com/jedisct1/libsodium/blob/b10be7a45895af682e98a27e8fadd21b511efd4c/src/libsodium/crypto_sign/ed25519/ref10/sign.c#L27), `prehashed` is true for init/update/final and false for detached.

**Comment by dnaq** [comment]
Fixed by #170, 9d73da785086d193c22475706fa1d42786eb8233

**Comment by aep** [comment]
uh this never got merged, did it?

**Comment by dnaq** [comment]
Not yet, will probably get merged this week.
