### ISSUE TITLE
Successful compile, but undefined references error when calling anything.

### ISSUE THREAD

**Issue by Hand-of-Cthulhu** [dnaq/sodiumoxide#182]
I am running rust in MSYS, after installing libsodium (64 bit), and setting the correct PKG_CONFIG_PATH, sodiumoxide compiles fine. But when I try to call something, e.g. `sodiumoxide::init()`, I got the error `error: linking with gcc failed: exit code: 1`

    ...\target\debug\deps\libsodiumoxide-555164969ab168a3.rlib(sodiumoxide-555164969ab168a3.0.o): In function 'sodiumoxide::crypto::stream::xchacha20::stream':
    ...\.cargo\registry\src\github.com-1ecc6299db9ec823\sodiumoxide-0.0.16\src\crypto\stream/stream_macros.rs:65: undefined reference to 'crypto_stream_xchacha20'

    ...\target\debug\deps\libsodiumoxide-555164969ab168a3.rlib(sodiumoxide-555164969ab168a3.0.o): In function 'sodiumoxide::crypto::stream::xchacha20::stream_xor':
    ...\.cargo\registry\src\github.com-1ecc6299db9ec823\sodiumoxide-0.0.16\src\crypto\stream/stream_macros.rs:85: undefined reference to 'crypto_stream_xchacha20_xor'

    ...\target\debug\deps\libsodiumoxide-555164969ab168a3.rlib(sodiumoxide-555164969ab168a3.0.o): In function 'sodiumoxide::crypto::stream::xchacha20::stream_xor_inplace':
    ...\.cargo\registry\src\github.com-1ecc6299db9ec823\sodiumoxide-0.0.16\src\crypto\stream/stream_macros.rs:104: undefined reference to 'crypto_stream_xchacha20_xor'

    ...\rust_keylogger\target\debug\deps\libsodiumoxide-555164969ab168a3.rlib(sodiumoxide-555164969ab168a3.0.o): In function 'sodiumoxide::crypto::stream::xchacha20::stream_xor_ic':
    ...\.cargo\registry\src\github.com-1ecc6299db9ec823\sodiumoxide-0.0.16\src\crypto\stream/stream_macros.rs:126: undefined reference to 'crypto_stream_xchacha20_xor_ic'

    ...\rust_keylogger\target\debug\deps\libsodiumoxide-555164969ab168a3.rlib(sodiumoxide-555164969ab168a3.0.o): In function 'sodiumoxide::crypto::stream::xchacha20::stream_xor_ic_inplace':
    ...\.cargo\registry\src\github.com-1ecc6299db9ec823\sodiumoxide-0.0.16\src\crypto\stream/stream_macros.rs:149: undefined reference to 'crypto_stream_xchacha20_xor_ic'

I tried installing the 32 bit libsodium as well just in case, but that didn't work either.
Any ideas?

**Comment by dnaq** [comment]
You’re running an old version of libsodium, please update to the latest version.
