### ISSUE TITLE
Expose selected primitives

### ISSUE THREAD

**Issue by geertj** [dnaq/sodiumoxide#195]
Currently the crate `libsodium-sys` defines string constants for the different cryptographic primitives provided, e.g. `crypto_hash_PRIMITIVE`, etc, but it appears these aren't re-exported by `libsodium` itself.

Having these would help with interoperability between different NaCL based applications by e.g. allowing a compile-time `assert!` that the expected primitives are used. Is there any particular reason these aren't exported? If not, I'm happy to create a pull request.

**Comment by dnaq** [comment]
The reasoning has been that a user that cares about the actual primitives used would use e.g. `crypto::secretbox::xsalsa2poly1305` instead of `crypto::secretbox`. That being said the documentation shows which primitive is being used as well.
