### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by Dev-Osmium** [dnaq/sodiumoxide#198]
Failed to install with following error

[https://hastebin.com/oqufamoqof.tex](https://hastebin.com/oqufamoqof.tex)

**Comment by vimmerru** [comment]
It doesn't support libsodium 1.0.12 that is present by default in the most of modern distros and macos. Is this project died?

**Comment by dnaq** [comment]
1. The issue has nothing to do with the libsodium
version, just that pkg-config doesn’t find libsodium
2. Are you serious? Do you think the project is dead since it doesn’t
support a really old version of libsodium?

**Comment by Dev-Osmium** [comment]
That is related to libsodium, it failed to install. I never said anything about the version.

**Comment by vimmerru** [comment]
@dnaq I am talking about libsodium 1.0.15 and 1.0.14. 1.0.12 is working fine. Sodiumoxide doesn’t support it because some symbols were removed and linking failed. 1.0.15 is default version in MacOS brew now and in new Ubuntu. As result builds doesn’t work on this platforms without tricks.

**Comment by dnaq** [comment]
Can you write an issue for that? Seems weird, I’ve had 1.0.15 on my
developer setup since it was released.

**Comment by dnaq** [comment]
Also, the Travis build scripts use 1.0.15
