### ISSUE TITLE
scrypt support

### ISSUE THREAD

**Issue by tarcieri** [dnaq/sodiumoxide#21]
It'd be nice if the `crypto_pwhash_scryptsalsa208sha256` and `crypto_pwhash_scryptsalsa208sha256_ll` APIs were exposed.

This is something I can work on myself if you'd like to see it added.

**Comment by dnaq** [comment]
Sorry that it has taken so long, I lost a lot of work due to hardware failure.

**Comment by tarcieri** [comment]
Me too, been meaning to work on this myself, but if you'd like to go for it, be my guest ;)

I saw that there's an implementation in rust-crypto as well (which confusingly shares the same "crypto" namespace)

**Comment by tarcieri** [comment]
@dnaq sweet!

**Comment by dnaq** [comment]
@tarcieri please take a look and see if you're happy with the exposed API. I'm open to changing it if needed.

**Comment by tarcieri** [comment]
Definitely good enough to get me started, thanks!
