### ISSUE TITLE
non-allocating primitives for asymmetricbox and secretbox

### ISSUE THREAD

**Issue by dnaq** [dnaq/sodiumoxide#24]
Right now the primitives used by asymmetricbox and secretbox return a Vec<u8> for ciphertexts and plaintexts. There are use-cases where dynamic memory allocation might not be possible, thus we need to add primitives that modify their arguments in-place.

Work is ongoing in the box_inplace branch, d1f6cbb6f21418c40286d118a3105c2dd0fe9f9f

**Comment by oconnor663** [comment]
The PR I just put up is an example implementation for secretbox. It might be a smaller change than what's in the `box_inplace` branch, though that's partly because it doesn't touch the box functions yet. Please let me know what you think.

**Comment by kcchu** [comment]
This issue was already fixed by commit c810136bdba20997d381fb127f0c935b6e48db22
