### ISSUE TITLE
slicing (discussion issue)

### ISSUE THREAD

**Issue by dnaq** [dnaq/sodiumoxide#35]
Previously all newtypes in sodiumoxide defined an `as_slice()` and an `as_mut_slice()` methods that could be used to access their contents. However since rust is moving away from those methods in general they were replaced by implementations of `Index<Range>`, `Index<RangeFrom>`, `Index<RangeTo>` and `Index<RangeFull>`, thus allowing a user to slice the newtypes using the range syntax. e.g. `newtype.as_slice()` => `&newtype[]` and also allowing users to do `&newtype[0..12]` to access part of a newtype. However I haven't implemented `IndexMut<...>` for any of the types yet, since I'm not sure if there's a use-case for mutable slices. Use-cases for mutable slices could be to implement nonces for specific network protocols (e.g. incrementing a nonce where part of it is fixed).

Also, do people see a need for `Index<Range(ε|From|To)>`, or do we only need an implementation for `RangeFull`?

**Comment by actimehl** [comment]
Simply because of the expectation that if slicing is supported all ranges should be supported, i'd support them all. Further if RangeFull is supported you can always double slice to a shorter range `let b = &a[][1..3]`, this would be only annoyance.

**Comment by dnaq** [comment]
I felt the same way because of symmetry, what do you think about mutable slices?
