### ISSUE TITLE
crates.io ? 

### ISSUE THREAD

**Issue by dirvine** [dnaq/sodiumoxide#43]
Is there any move to put this library on crates.io or would there be any resistance to another project forking and doing this? Of course if this project were on crates.io it would make it much simpler to use and in fact is a requirement I think for any crate on crates.io and the like to be able to use it.

Thanks for your time.

**Comment by actimehl** [comment]
I think libsodium-sys and sodiumoxide should be put on crates.io

**Comment by dnaq** [comment]
I agree. I tried to upload it to crates.io a while ago, but crates.io didn't seem to handle subprojects (libsodium-sys is a subproject of sodiumoxide). If anyone knows how to work the Cargo.toml magic in order to make it work I would be grateful.

**Comment by actimehl** [comment]
Maybe sodiumoxide and libsodium-sys have to be uploaded as independent projects.

**Comment by dirvine** [comment]
It will be much easier if libsodium-sys were a separate crate and then sodiumoxide used it as a crate for sure.

**Comment by actimehl** [comment]
They are separate crates but live in the same repo.

**Comment by dnaq** [comment]
@actimehl I think they might have to be, but I haven't found out how to have Cargo depend on the in-tree libsodium-sys when building locally and depending on a crates.io version when installing with cargo

There is probably a smart way to solve this, but I haven't found it yet.

**Comment by actimehl** [comment]
Look at https://github.com/alexcrichton/git2-rs for example. There are https://crates.io/crates/git2 and https://crates.io/crates/libgit2-sys. I think the *-sys packages has to be uploaded first.

**Comment by dnaq** [comment]
SodiumOxide is now on crates.io

**Comment by dirvine** [comment]
Fantastic, Thx very much
