### ISSUE TITLE
Issues blocking rust-1.0-beta compatibility

### ISSUE THREAD

**Issue by dnaq** [dnaq/sodiumoxide#51]
For now sodiumoxide is compatible with rust-nightly, but not with rust-1.0-beta. There are three reasons for this, only one of which is critical.

1. `std::intrinsics::volatile_set_memory()` is unstable, and thus not available in the rust beta. This is the critical issue, I'm not comfortable with not having this intrinsics since sodiumoxide is a cryptographic library and we need reasonable guarantees that key memory will be zeroed out when the keys go out of scope.
2. `std::vec::Vec::push_all(buf)` is unstable. This can be easily replaced with `extend(buf.iter().cloned())` with a small cost in performance (as shown by earlier benchmarks).
3. The `test` crate is unstable, so all the benchmarks have to be stripped from the code to be able to build it with the rust beta.

I'm keeping this issue open for now for discussion, I'm ok with 2 and 3, but 1 stops us from being able to support the rust beta.

**Comment by kmcallister** [comment]
> The `test` crate is unstable, so all the benchmarks have to be stripped from the code to be able to build it with the rust beta.

Seems like they should be behind a Cargo feature, then.

> I'm not comfortable with not having this intrinsics since sodiumoxide is a cryptographic library and we need reasonable guarantees that key memory will be zeroed out when the keys go out of scope.

How about calling into C?

**Comment by PeterReid** [comment]
> std::intrinsics::volatile_set_memory() is unstable, and thus not available in the rust beta.

Why not use sodium_memzero for this?

**Comment by dnaq** [comment]
I'll go with `sodium_memzero()`. Thanks for the tip, I've mostly focused on the NaCl-subset of libsodium, so I had all but forgotten about `sodium_memzero()`.

**Comment by tarcieri** [comment]
@dnaq `sodium_malloc` is pretty cool too :wink:

**Comment by dnaq** [comment]
@tarcieri `sodium_malloc()` is indeed interesting, but it should probably be wrapped behind a `SecureBox` or something like that to be usable in a good way in rust. Also a design goal of sodiumoxide is to be usable on embedded systems as well, so we need to be able to stack allocate keys, nonces, et.al as well.
