### ISSUE TITLE
rename asymmetricbox to box_

### ISSUE THREAD

**Issue by dnaq** [dnaq/sodiumoxide#54]
In NaCl (and libsodium) the asymmetric box primitive is named `crypto_box()`. However, since `box` is a reserved keyword in rust we can't name our corresponding module `crypto::box`. At the moment the module is named `crypto::asymmetricbox`.

Would you agree with the module being renamed to `crypto::box_` or do you think the name should stay the same?

**Comment by jedisct1** [comment]
In Scala, reserved words can still be used as identifiers by enclosing them in backquotes.
Maybe a good opportunity to propose a RFC to support something similar in Rust?

Meanwhile, my vote would go to `crypto::box_` for consistency.

**Comment by dnaq** [comment]
I agree with `crypto::box_`, keeping the issue open for a while to see if anyone else chimes in.

**Comment by james-darkfox** [comment]
I disagree with the movement to `crypto::box_`; instead, I think it should be `sodiumoxide::cryptobox`.
Note that there is no `::crypto`, the only other module present for sodiumoxide is 'randombytes' - is there any reason to why they need to be separate?

My recommendation is that `crypto` and `randombytes` get merged into `sodiumoxide` - and then renaming box_ to cryptobox.

More to the point; if `cryptobox` gets expanded to `crypto::box_` - then why not `secretbox` expand to `secret::box_` ? The whole library is purposed for crypto!

Side suggestion: Check out 'secrets' - this should probably be integrated into sodiumoxide and used for all keys generated by key_gen!

**Comment by dnaq** [comment]
@james-darkfox I've tried to follow the naming conventions from the original NaCl library where the names are `crypto_box`, `crypto_secretbox`, `crypto_auth`, et.al. So I've tried to keep the original namespacing.

Do you have a link for secrets?, It's kind of a hard word to google for. I'm guessing that it might be some kind of secure memory allocation library. If so, then sodium exposes primitives for secure memory allocation, and I've been thinking about implementing a `SecureBox`-interface for using those interfaces. One of the reasons I haven't is that the discussion about placement new hasn't landed yet, and without placement new memory might still end up on the stack.

**Comment by james-darkfox** [comment]
Sorry about the vagueness of 'secrets' however, as a hint - search for it under http://crates.io/. ;)

**Comment by dnaq** [comment]
> Sorry about the vagueness of 'secrets' however, as a hint - search for it under http://crates.io/. ;)

I just looked it up, it looks similar to my `Securebox`-approach. However, that was usable for all types (not just byte-slices), but I paused development because of the placement new issue.

> As for the naming convention; as my second vote: maybe we should have some aliased pub uses in lib.rs 

As of now we have `pub use` statements in all submodules, e.g. `crypto::secretbox` has a `pub use self::xsalsa20poly1305::*;`

> what are your thoughts for using Traits where NaCl/libsodium have already defined standard interfaces

I was investigating using traits, but I didn't manage to create a good abstraction using them (since to have a trait we need to have a type to dispatch on). It would be possible to have for example a `SecretBox` trait and creating instances with associated types, but I'm not sure if that would give us any advantages as compared to the current interface.

> On a sidenote: the box keyword has been marked as experimental

I'm keeping my eyes open, and will claim the name if `box` stops being a reserved keyword. However I believe that the main reason for `box` being experimental is that the placement new issue isn't sorted out yet.

**Comment by james-darkfox** [comment]
All good; just like to respond to a particular section - traits.

Although sodiumoxide is currently (and probably always will be) libsodium; it would be nice to use as a backbone for other rust crypto related libraries - such as for example norx-rs to be implemented against the same trait and maintaining the interface while not being libsodium at all.
