### ISSUE TITLE
Incorrect function return types (Option instead of Result)

### ISSUE THREAD

**Issue by JanLikar** [dnaq/sodiumoxide#78]
asymetricbox::open(), secretbox::open() and pwhash::gen_key() return Option enum instead of Result.

The following links suggest that Result should be returned when a function is not expected to fail under normal circumstances. Result::Err signifies an unexpected condition that must be handled, therefore it is a better fit for a cryptographic library.

[Reddit thread](https://www.reddit.com/r/rust/comments/2j0k21/rust_option_vs_result/)
[Rust docs](http://doc.rust-lang.org/std/result/#result-and-option)

I can correct this issue, if you are willing to pull the fixes.

**Comment by dnaq** [comment]
Thanks for the bug report. It seems like best practices in rust have evolved since I started writing sodium oxide. Also thanks for the willingness of sending a pull request, but I'll probably implement the changes right now instead.
