### ISSUE TITLE
crypto::stream APIs could accept slice as key and nonce

### ISSUE THREAD

**Issue by zonyitoo** [dnaq/sodiumoxide#79]
Currently, as defined in `crypto/stream/stream_macros.rs`, the APIs accepts a `&Key` and `&Nonce` as parameters, that makes impossible to use `Vec` to dynamically allocate and store the key and nonce.

So I propose the APIs could accept slices `&[u8]` as parameters, and use `assert` to ensure it has the correct length.

**Comment by dnaq** [comment]
All `Key` and `Nonce` types implement a `from_slice()` function that could be used for that use case. Generally I prefer to have separate types, at least for secret data, since we want to try to zero out memory when the objects go out of scope.

**Comment by zonyitoo** [comment]
Well.. Your document on rust-ci is outdated.

**Comment by dnaq** [comment]
That's weird, it's supposed to auto update every time I push to the repo.
