### ISSUE TITLE
Please add the missing *_xor_ic APIs in crypto::stream

### ISSUE THREAD

**Issue by zonyitoo** [dnaq/sodiumoxide#80]
For example

```
crypto_stream_salsa20_xor_ic
crypto_stream_chacha20_xor_ic
```

**Comment by dnaq** [comment]
I've not implemented those yet, since libsodium only defines those functions for Salsa20 and Chacha20 (XSalsa20 and AES-128-CTR are missing). If there is enough interest I might add them though.

**Comment by Cyberunner23** [comment]
crypto_stream_xsalsa20_xor_ic is present in libsodium 1.0.3 even though its not in the documentation yet, this can be found in code [here](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_stream/xsalsa20/ref/xor_xsalsa20.c) with crypto_stream_xor_ic being redefined as crypto_stream_xsalsa20_xor_ic [here](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_stream/xsalsa20/ref/api.h)

**Comment by bnewbold** [comment]
I've just now run in to the missing `crypto_stream_*_xor_ic` issue as well (for my use case, `crypto_stream_xsalsa20_xor_ic`).

The only rust ecosystem way I've seen to get access to this function are the raw (unsafe) bindings in `libsodium-ffi`. I will probably use sodiumoxide patched with @quininer's implementation for now.

**Comment by Neurrone** [comment]
Same here, wanted to use this function for random access to sspecific blocks of a larger file.

**Comment by dnaq** [comment]
Closed by c630296ac994e59e04455b50975ed8ddacc17c46
