### ISSUE TITLE
Use output paramenter for not-inplace crypto::stream algorithms

### ISSUE THREAD

**Issue by zonyitoo** [dnaq/sodiumoxide#81]
For example, the `stream_xor` could be written as the following

```rust
pub fn stream_xor(m: &[u8],
                  nonce &Nonce,
                  key: &Key,
                  out: &mut [u8])
```

which could possibly reuse the allocated output buffer.

**Comment by dnaq** [comment]
Couldn't you use 'stream_xor_inplace()' for that?

**Comment by zonyitoo** [comment]
Of course, `stream_xor_inplace` is a solution, I just suggest the `stream_xor` may shouldn't allocate memory inside ...

**Comment by dnaq** [comment]
I prefer to not increase the api size 'stream_xor()' is meant to be the easy api and 'stream_xor_inplace()' is meant to be more of a power user api. TBH I don't see any need for an extra api in between them in complexity.
