### ISSUE TITLE
Put documentation on gh-pages

### ISSUE THREAD

**Issue by dnaq** [dnaq/sodiumoxide#83]
The travis-ci script in this repository contains a hook for updating the documentation that is hosted on rust-ci. The hook seems to run, but for some reason the actual documentation isn't updated.

I've tried readding the hook, I've also removed the project from rust-ci and added it again, but it's still not updating.

**Comment by dirvine** [comment]
There were some changes a while back, we use github itself to host crate docs and it works very well. You are more than welcome to copy our script if it helps. https://github.com/maidsafe/QA/blob/master/Bash%20Scripts/Travis/deploy_gh-pages.sh (also adds coverage if you get a coveralls.io account)
