### ISSUE TITLE
AEAD functions

### ISSUE THREAD

**Issue by perfaram** [dnaq/sodiumoxide#86]
Hi !
First, thanks for the work, it's really nice.
I'm migrating a C project to Rust to learn the latter... Unfortunately, I don't really understand how I'm supposed to call : `crypto_aead_chacha20poly1305_encrypt`. 
Any pointers ? Also, please *explain like I'm 5*.

**Comment by dnaq** [comment]
At the moment sodiumoxide doesn't expose high level bindings for the aead primitives. Your best bet at the moment is to use the low level bindings in `libsodium-sys`.

**Comment by perfaram** [comment]
OK, thanks !
