### ISSUE TITLE
Incorrect check for sodium_init() return value

### ISSUE THREAD

**Issue by stouset** [dnaq/sodiumoxide#88]
The [documentation being unclear](https://github.com/jedisct1/libsodium/issues/298) has tripped me up, too. `sodium_init()` returns `0` if it was initialized, `1` if it was already initialized, and `-1` on failure. Currently, sodiumoxide checks that [`sodium_init() == 0`](https://github.com/dnaq/sodiumoxide/blob/master/src/lib.rs#L63), which fails on the non-error case of the library already having been initialized.

**Comment by dnaq** [comment]
Thanks. Nice catch.
