### ISSUE TITLE
Usage of edwards25519sha512batch functions strongly discouraged

### ISSUE THREAD

**Issue by Fraser999** [dnaq/sodiumoxide#96]
The libsodium owner has strongly suggested that the `edwards25519sha512batch` should not be used (see comment at https://github.com/jedisct1/libsodium/issues/328)

I think the recommended replacements are in https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_sign.h

**Comment by dnaq** [comment]
You are correct. Let me quote from the sodiumoxide documentation:

> crypto_sign_edwards25519sha512batch is a prototype. It has been replaced with Ed25519 and is only kept here for compatibility reasons.

`crypto::sign` in sodiumoxide is `crypto::sign::ed25519`. I will add a deprecated attribute to `crypto::sign::edwards25519sha512batch` as soon as `#[deprecated]` lands in rust stable.
