### ISSUE TITLE
Nonces should not be `Copy`

### ISSUE THREAD

**Issue by drbo** [dnaq/sodiumoxide#99]
Nonces should NEVER be reused.  Therefore, they should not implement `Copy`.

**Comment by dnaq** [comment]
Yes, Nonces should never be reused. However not allowing them to implement Copy has other issues. Most cryptographic protocols require the receiver to get knowledge of the Nonce for example, and disallowing Copy makes the ergonomics of putting Nonces in network packets much worse. There are a lot of other examples where non-Copy Nonces lead to much more verbose, and not more secure, code. I don't feel that Copy is the correct mechanism for hindering nonce reuse.
